# Generated by Django 3.2.6 on 2021-08-03 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام ')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('comment', models.CharField(max_length=500, verbose_name='کامنت')),
                ('activate', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت کامنت')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_blog.post')),
            ],
        ),
    ]
